# docker run --name api-gym-pass-style-pg -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker -e POSTGRESQL_DATABASE=apigym -p 5432:5432 bitnami/postgresql:latest
version: '3'

services: 
  api-gym-pass-style-pg:
    image: bitnami/postgresql:latest
    ports: 
      - 5432:5432
    environment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apigym